# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
  pro0 = {path = "pro0"}
  pro1 = {path = "pro1"}

[package]
  cjc-version = "0.41.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "test"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[profile]
  build = {incremental = false, lto = "full"}
  customized-option = {}
  [profile.bench]
    build = {lto = "full"}
  [profile.run]
    env = {}
  [profile.test]
    build = {lto = "full"}
