# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
  a={path="./a"}
  b={path="./b"}
[package]
  cjc-version = "0.49.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "root"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  script-dir = "./tempbb"
  version = "1.0.0"
  package-configuration = {}

