# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[ffi.c.test01]
  path = "./"

[package]
  cjc-version = "1.0.0"
  description = "nothing here"
  name = "demo"
  output-type = "executable"
  version = "1.0.0"

