[package]
  cjc-version = "1.0.0"
  name = "demo"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  output-type = "dynamic"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[profile.build.combined]
  demo = "dynamic"
