# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[profile]
experimental = true

[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "bin_deps"
  output-type = "executable"
  override-compile-option = ""
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}


[target.x86_64-unknown-linux-gnu]
  compile-option = "-O1"

[target.x86_64-unknown-linux-gnu.bin-dependencies]
  package-option = { "dep" = "dep/target/release/dep/big/product/dep.cjo" }
  path-option = ["dep/target/release/dep/big/product"]

[target.x86_64-unknown-linux-gnu.debug.bin-dependencies]
  package-option = { "dep" = "dep/target/release/dep/big/product/dep.cjo" }
  path-option = ["dep/target/release/dep/big/product"]

[target.aarch64-unknown-linux-gnu]
  compile-option = "-O1"

[target.aarch64-unknown-linux-gnu.bin-dependencies]
  package-option = { "dep" = "dep/target/release/dep/big/product/dep.cjo" }
  path-option = ["dep/target/release/dep/big/product"]

[target.aarch64-unknown-linux-gnu.debug.bin-dependencies]
  package-option = { "dep" = "dep/target/release/dep/big/product/dep.cjo" }
  path-option = ["dep/target/release/dep/big/product"]

[target.x86_64-w64-mingw32]
  compile-option = "-O1"

[target.x86_64-w64-mingw32.bin-dependencies]
  package-option = { "dep" = "dep/target/release/dep/big/product/dep.cjo" }
  path-option = ["dep/target/release/dep/big/product"]

[target.x86_64-w64-mingw32.debug.bin-dependencies]
  package-option = { "dep" = "dep/target/release/dep/big/product/dep.cjo" }
  path-option = ["dep/target/release/dep/big/product"]

[target.x86_64-apple-darwin]
  compile-option = "-O1"

[target.x86_64-apple-darwin.bin-dependencies]
  package-option = { "dep" = "dep/target/release/dep/big/product/dep.cjo" }
  path-option = ["dep/target/release/dep/big/product"]

[target.x86_64-apple-darwin.debug.bin-dependencies]
  package-option = { "dep" = "dep/target/release/dep/big/product/dep.cjo" }
  path-option = ["dep/target/release/dep/big/product"]

[target.aarch64-apple-darwin]
  compile-option = "-O1"

[target.aarch64-apple-darwin.bin-dependencies]
  package-option = { "dep" = "dep/target/release/dep/big/product/dep.cjo" }
  path-option = ["dep/target/release/dep/big/product"]

[target.aarch64-apple-darwin.debug.bin-dependencies]
  package-option = { "dep" = "dep/target/release/dep/big/product/dep.cjo" }
  path-option = ["dep/target/release/dep/big/product"]

[target.aarch64-linux-ohos]
compile-option = "-B${OHOS_ROOT}/out/generic_generic_arm_64only/hisi_all_phone_standard/obj/third_party/musl/usr/lib/aarch64-linux-ohos -B${OHOS_ROOT}/prebuilts/clang/ohos/windows-x86_64/llvm/bin -L${OHOS_ROOT}/prebuilts/clang/ohos/windows-x86_64/llvm/lib/clang/15.0.4/lib/aarch64-linux-ohos -L${OHOS_ROOT}/prebuilts/clang/ohos/windows-x86_64/llvm/lib/aarch64-linux-ohos -L${OHOS_ROOT}/out/generic_generic_arm_64only/hisi_all_phone_standard/obj/third_party/musl/usr/lib/aarch64-linux-ohos -L${OHOS_ROOT}/out/generic_generic_arm_64only/hisi_all_phone_standard/thirdparty/openssl"
