# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "0.35.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "test"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[target]
  [target.x86_64-unknown-linux-gnu]
    [target.x86_64-unknown-linux-gnu.bin-dependencies]
      path-option = []
      [target.x86_64-unknown-linux-gnu.bin-dependencies.package-option]
        "pro1.xoo" = "./pro1/target/release/pro1/pro1.xoo.cjo"
        "pro1.zoo" = "./pro1/target/release/pro1/pro1.zoo.cjo"
        "pro1.yoo" = "./pro1/target/release/pro1/pro1.yoo.cjo"

    [target.aarch64-unknown-linux-gnu.bin-dependencies.package-option]
      "pro1.xoo" = "./pro1/target/release/pro1/pro1.xoo.cjo"
      "pro1.zoo" = "./pro1/target/release/pro1/pro1.zoo.cjo"
      "pro1.yoo" = "./pro1/target/release/pro1/pro1.yoo.cjo"
    
    [target.x86_64-apple-darwin.bin-dependencies.package-option]
      "pro1.xoo" = "./pro1/target/release/pro1/pro1.xoo.cjo"
      "pro1.zoo" = "./pro1/target/release/pro1/pro1.zoo.cjo"
      "pro1.yoo" = "./pro1/target/release/pro1/pro1.yoo.cjo"

    [target.aarch64-apple-darwin.bin-dependencies.package-option]
      "pro1.xoo" = "./pro1/target/release/pro1/pro1.xoo.cjo"
      "pro1.zoo" = "./pro1/target/release/pro1/pro1.zoo.cjo"
      "pro1.yoo" = "./pro1/target/release/pro1/pro1.yoo.cjo"

    [target.aarch64-linux-ohos.bin-dependencies.package-option]
      "pro1.xoo" = "./pro1/target/release/pro1/pro1.xoo.cjo"
      "pro1.zoo" = "./pro1/target/release/pro1/pro1.zoo.cjo"
      "pro1.yoo" = "./pro1/target/release/pro1/pro1.yoo.cjo"

  [target.cjvm]
    [target.cjvm.bin-dependencies]
      path-option = []
      [target.cjvm.bin-dependencies.package-option]
        "pro1.xoo" = "./pro1/target/release/pro1/pro1.xoo.cjo"
        "pro1.zoo" = "./pro1/target/release/pro1/pro1.zoo.cjo"
        "pro1.yoo" = "./pro1/target/release/pro1/pro1.yoo.cjo"
