# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.0.0"
  name = "demo"
  version = "1.0.0"
  output-type = "dynamic"
  description = "nothing here"
  tag = ["tag1", "tag2", "tag3", "tag4", "tag5", "tag6"]
  category = ["Network", "Database Driver", "Data Encapsulation and Transfer", "Data Analysis", "Database Framework", "Object Storage"]