# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.0.0"
  name = "test_install_demo"
  version = "1.0.0"
  description = "nothing here"
  output-type = "executable"
  include = ["src"]

[dependencies]
  test_repo_1 = "1.0.0"
  test_repo_3 = "1.0.0"
