# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "test"
  organization = "org2"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
  scripts = {}

[target.x86_64-unknown-linux-gnu.dependencies]
  "org2::pro0" = {path = "pro0"}
  pro1 = {path = "pro1"}

[target.aarch64-unknown-linux-gnu.dependencies]
  "org2::pro0" = {path = "pro0"}
  pro1 = {path = "pro1"}

[target.x86_64-w64-mingw32.dependencies]
  "org2::pro0" = {path = "pro0"}
  pro1 = {path = "pro1"}
  

[target.x86_64-apple-darwin.dependencies]
  "org2::pro0" = {path = "pro0"}
  pro1 = {path = "pro1"}

[target.aarch64-apple-darwin.dependencies]
  "org2::pro0" = {path = "pro0"}
  pro1 = {path = "pro1"}

