[default]
APIStrategy = "Full"
GenericTypeStrategy = "None"

[[package]]
name = "cjworld"
APIStrategy = "Full"
GenericTypeStrategy = "Partial"
excluded_apis = [
]
generic_object_configuration = [
    { name = "GenericEnum", type_arguments = ["Int32", "Float64"] },
    { name = "GenericEnum<Int32>", symbols = [
        "printValue",
        "setValue",
        "value"
    ]}
    { name = "GenericEnum<Float64>", symbols = [
        "printValue",
        "setValue",
        "value"
    ]}
]
