[default]
APIStrategy = "Full"
GenericTypeStrategy = "None"

[[package]]
name = "cjworld"
APIStrategy = "Full"
GenericTypeStrategy = "Partial"
excluded_apis = [
]
generic_object_configuration = [
    { name = "GenericInterface", type_arguments = ["Int32, Int64", "Float64, Int32"] },
    { name = "GenericInterface<Int32, Int64>", symbols = [
        "setValue",
        "getValue",
        "foo",
        "koo",
        "gooT",
        "gooU"
    ]},
    { name = "GenericInterface<Float64, Int32>", symbols = [
        "setValue",
        "getValue",
        "foo",
        "koo",
        "gooT",
        "gooU"
    ]}
]
tuple_configuration = [
    "(Int32, Int64)",
    "(Float64, Int32)"
]
