# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[workspace]
members = ["aoo", "boo"]
link-option=""
build-members = ["aoo", "boo"] 
test-members = ["aoo"] 
compile-option = "--warn-off all" 
target-dir = "temp_target" 

[target.cjvm]
  override-compile-option = "-O2"

[target.x86_64-unknown-linux-gnu]
  override-compile-option = "-O2"

[target.x86_64-w64-mingw32]
  override-compile-option = "-O2"

[target.x86_64-apple-darwin]
  override-compile-option = "-O2"

[target.aarch64-apple-darwin]
  override-compile-option = "-O2"

[target.aarch64-unknown-linux-gnu]
  override-compile-option = "-O2"

[target.aarch64-linux-ohos]
  override-compile-option = "-O2"
