# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "demo"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
  scripts = {}

[target.x86_64-unknown-linux-gnu]
  compile-option = "-O1"

[target.x86_64-unknown-linux-gnu.bin-dependencies]
  package-option = { "pro1.xoo" = "pro1/target/release/pro1/pro1.xoo.cjo" }
  path-option = ["pro1/target/release/pro1"]

[target.x86_64-unknown-linux-gnu.debug.bin-dependencies]
  package-option = { "pro1.xoo" = "pro1/target/release/pro1/pro1.xoo.cjo" }
  path-option = ["pro1/target/release/pro1"]

[target.x86_64-w64-mingw32]
  compile-option = "-O1"

[target.x86_64-w64-mingw32.bin-dependencies]
  package-option = { "pro1.xoo" = "pro1/target/release/pro1/pro1.xoo.cjo" }
  path-option = ["pro1/target/release/pro1"]

[target.x86_64-w64-mingw32.debug.bin-dependencies]
  package-option = { "pro1.xoo" = "pro1/target/release/pro1/pro1.xoo.cjo" }
  path-option = ["pro1/target/release/pro1"]

[target.x86_64-apple-darwin]
  compile-option = "-O1"

[target.x86_64-apple-darwin.bin-dependencies]
  package-option = { "pro1.xoo" = "pro1/target/release/pro1/pro1.xoo.cjo" }
  path-option = ["pro1/target/release/pro1"]

[target.x86_64-apple-darwin.debug.bin-dependencies]
  package-option = { "pro1.xoo" = "pro1/target/release/pro1/pro1.xoo.cjo" }
  path-option = ["pro1/target/release/pro1"]

[target.aarch64-apple-darwin]
  compile-option = "-O1"

[target.aarch64-apple-darwin.bin-dependencies]
  package-option = { "pro1.xoo" = "pro1/target/release/pro1/pro1.xoo.cjo" }
  path-option = ["pro1/target/release/pro1"]

[target.aarch64-apple-darwin.debug.bin-dependencies]
  package-option = { "pro1.xoo" = "pro1/target/release/pro1/pro1.xoo.cjo" }
  path-option = ["pro1/target/release/pro1"]
