# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
  demo = {path = "../demo"}

[package]
  cjc-version = "1.0.0"
  name = "b"
  organization = ""
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  script-dir = ""
  output-type = "dynamic"
  src-dir = "src"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[profile.build.combined]
  b = "dynamic"
