# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  target-dir = ""
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  lto = ""
  name = "test"
  organization = "cangjie"
  output-type = "executable"
  src-dir = ""
  version = "1.0.0"
  [package.cross-compile-configuration]
  [package.foreign-requires]
  [package.package-configuration]
  [package.package-requires]
    path-option = []
    [package.package-requires.package-option]
  [package.scripts]
  [package.test-configuration]
