# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
p1 = {path = "p1"}
p2 = {path = "p2"}
p3 = {path = "p3"}
[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "b"
  output-type = "executable"
  override-compile-option = ""
  version = "1.0.0"

