[default]
APIStrategy = "Full"
GenericTypeStrategy = "None"

[[package]]
name = "cjworld"
APIStrategy = "Full"
GenericTypeStrategy = "Partial"
excluded_apis = [
]
generic_object_configuration = [
    { name = "GenericClass", type_arguments = ["Int32, Int64", "Float64, Int32"] },
    { name = "GenericClass<Int32, Int64>", symbols = [
        "GenericClass",
        "setValue",
        "getValue"
    ]},

    { name = "GenericClass<Float64, Int32>", symbols = [
        "GenericClass",
        "setValue",
        "getValue"
    ]}
]
tuple_configuration = [
    "(Int32, Int64)",
    "(Float64, Int32)"
]
