# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[profile]
  experimental = true
  
[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "Keels Package"
  link-option = ""
  name = "testing"
  output-type = "dynamic"
  target-dir = ""
  version = "1.0.0"
  [package.package-configuration]
  [package.scripts]


[[source-set]]
name = "common"
src-dir = "./common"
features = []

[[source-set]]
name = "windows"
src-dir = "./windows/cangjie"
features = ["os.windows"]

