# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "test"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

# use static stdx path
[target]
  [target.x86_64-w64-mingw32]
    compile-option = ""
    link-option ="-lcrypto"
  [target.x86_64-w64-mingw32.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}"]

  [target.x86_64-unknown-linux-gnu]
    compile-option = ""
    link-option ="-ldl"
  [target.x86_64-unknown-linux-gnu.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}"]

  [target.aarch64-unknown-linux-gnu]
    compile-option = ""
    link-option ="-ldl"
  [target.aarch64-unknown-linux-gnu.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}"]

  [target.x86_64-apple-darwin]
    compile-option = ""
    link-option ="-ldl"
  [target.x86_64-apple-darwin.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}"]

  [target.aarch64-apple-darwin]
    compile-option = ""
    link-option ="-ldl"
  [target.aarch64-apple-darwin.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}"]



