# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.0.0"
  name = "typing"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}
  always-enabled-features = ["os.linux", 3, "os.windows", "not .. qname"]

[dependencies]

[profile]
  experimental = true

[[feature]]
name = 43
mapping = 42

[[feature]]
name = "qname.good"
mapping = []

[[feature]]
name = "qname"

[[feature]]
name = "not qname"
mapping = [ "not qname", "qname", "also.qname", " this . is.also . qname", "this .. is .. not . qname"]

[[feature]]
names = "expected.array.qname"

[[feature]]
names = ["qname", "also.qname", "this . is.also .qname", "this .. is .. not . qname"]

[[source-set]]
name = "common"
src-dir = "./common"
features = []
product = false

[[source-set]]
name = 3
src-dir = ["./common"]
features = "qname"
product = 2

[[source-set]]
name = 3
src-dir = "./common"
features = []
product = false

[[source-set]]
src-dir = ""
features = []
