# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "1.0.0"
  description = "nothing here"
  name = "demo"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
  scripts = {}
  compile-option = "-O1"
  link-option = "-s"

[target.x86_64-w64-mingw32]
  compile-option = "-O2"
  link-option = "-s"

[target.x86_64-w64-mingw32.debug]
  compile-option = "-Woff all"
  link-option = "-s"
