[default]
APIStrategy = "Full"
GenericTypeStrategy = "None"

[[package]]
name = "genericClass"
APIStrategy = "Full"
GenericTypeStrategy = "Partial"
excluded_apis = [
]
generic_object_configuration = [
    { name = "GenericClass", type_arguments = ["Int32, Int64", "Float64, Int32"] },
    { name = "GenericClass<Int32, Int64>", symbols = [
        "GenericClass",
        "valueT",
        "valueU",
        "setValueT"
        "setValueU",
        "setUGetValueT",
        "setTGetValueU",
        "getValueU",
        "getValueT"
    ]},

    { name = "GenericClass<Float64, Int32>", symbols = [
        "GenericClass",
        "valueT",
        "valueU",
        "setValueT",
        "setValueU",
        "setTGetValueU",
        "setUGetValueT",
        "getValueU",
        "getValueT"
    ]}
]
