# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.
 
[[packages]]
filters = { include = ["NS.+", "int.*"] }
package-name = "objc.foundation"

[[packages]]
filters = { include = "M.*" }
package-name = "cjworld"

[output-roots.default]
path = "src"

[sources.all]
paths = ["src/objc/M1.h", "src/objc/M2.h"]

[sources-mixins.default]
sources = [".*"]
arguments-append = [
    "-F", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks",
    "-isystem", "/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include",
    "-isystem", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include",
    "--target=arm64-apple-ios",
    "-DTARGET_OS_IPHONE"
]
