# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
  pro1 = {path = "./pro1"}

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "b"
  output-type = "executable"
  override-compile-option = ""
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  [package.package-configuration]
    a = {compile-option = "", output-type = ""}

[profile]
  bench = {}
  build = {incremental = false, lto = ""}
  customized-option = {cfg1 = "--cfg=\"feature1=lion, feature2=cat\"", cfg2 = "--cfg=\"feature1=lion, feature2=dog\"", cfg3 = "--cfg=\"feature1=tiger, feature2=cat\"", cfg4 = "--cfg=\"feature1=tiger, feature2=dog\"", cfg6 = "-g"}
  test = {}
  [profile.run]
    env = {}
