# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "0.60.4"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "demo"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
  scripts = {}

[target.x86_64-unknown-linux-gnu.debug.ffi.c]
    test01= { path = "./" }

[target.aarch64-unknown-linux-gnu.debug.ffi.c]
    test01= { path = "./" }

[target.x86_64-w64-mingw32.debug.ffi.c]
    test01= { path = "./" }

[target.x86_64-apple-darwin.debug.ffi.c]
    test01= { path = "./" }

[target.aarch64-apple-darwin.debug.ffi.c]
    test01= { path = "./" }

[target.aarch64-linux-ohos.ffi.c]
    test01= { path = "./" }

[target.cjvm.ffi.c]
    test01= { path = "./" }