# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.
[[package]]
name = "UNNAMED"
APIStrategy = "Full"
GenericTypeStrategy = "Partial"

tuple_configuration = [
    "(Int, Bool)",
    "(Float32, Int32)",
    "(Bool, Int, Int8, Int16, Int32, Int64, UInt16, Float32, Float64)",
]
lambda_patterns = [
#    { signature = "(Int64, Bool) -> Int64" },
#    { signature = "(Int32, Int32) -> Unit" },
    { signature = "(Int64, Bool) -> Int64" },
    { signature = "(Int32) -> Int32" },
]
generic_object_configuration = [
	{ name = "CangjieGenericClass", type_arguments = ["Int64"] },
	{ name = "CangjieGenericClass<Int64>", symbols = ["instanceMemberFunction"] },
	{ name = "CangjieGenericStruct", type_arguments = ["Bool, Int8, Int16, Int32, Int64, UInt16, Float32, Float64"] },
	{ name = "CangjieGenericStruct<Bool, Int8, Int16, Int32, Int64, UInt16, Float32, Float64>", symbols = ["instanceMemberFunction"] },
	{ name = "CangjieGenericEnum", type_arguments = ["Float64"] },
	{ name = "CangjieGenericEnum<Float64>", symbols = ["instanceMemberFunction"] },
    { name = "CangjieGenericInterface", type_arguments = ["Bool, Int8, Int16, Int32, Int64, UInt16, Float32, Float64"] },
	{ name = "CangjieGenericInterface<Bool, Int8, Int16, Int32, Int64, UInt16, Float32, Float64>", symbols = ["instanceMemberFunctionWithoutDefaultImpl"] },
]
