[default]
APIStrategy = "Full"
GenericTypeStrategy = "None"

[[package]]
name = "cjworld"
APIStrategy = "Full"
GenericTypeStrategy = "Partial"
excluded_apis = [
]
generic_object_configuration = [
    { name = "GenericClass", type_arguments = ["Float64", "Lobg"] },
    { name = "GenericClass<Float64>", symbols = [
        "getValue",
        "GenericClass",
        "value",
        "setValue"
    ]},

    { name = "GenericClass<Lobg>", symbols = [
        "getValue",
        "GenericClass",
        "value",
        "setValue"
    ]}
]
