[default]
APIStrategy = "Full"
GenericTypeStrategy = "None"

[[package]]
name = "cjworld"
APIStrategy = "Full"
GenericTypeStrategy = "Partial"
excluded_apis = [
]
generic_object_configuration = [
    { name = "A", type_arguments = ["Int64"] },
    { name = "A<Int64>", symbols = [
        "E",
        "f",
        "p"
    ]}
]