# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.0.0"
  name = "demo"
  version = "1.0.0"
  output-type = "executable"

[dependencies]
  test_output_1 = "1.0.0"
  test_output_2 = "1.0.0"
