[package]
  cjc-version = "1.0.5"
  name = "demo"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  dep = { path = "./dep"}

[target.x86_64-mingw32.bin-dependencies]
  path-option = ["./dep/target/x86_64-w64-mingw32/release/dep"]
