[default]
APIStrategy = "Full"
GenericTypeStrategy = "None"

[[package]]
name = "cj"
APIStrategy = "Full"
GenericTypeStrategy = "Partial"
excluded_apis = [
]
generic_object_configuration = [
    { name = "A", type_arguments = ["Int32"] },
    { name = "A<Int32>", symbols = [
        "goo"
    ]}
]