# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
  "org_old::pro1" = { path = "./pro1" }

[replace]
  "org_old::dep" = { path = "../dep-new" }

[target.x86_64-unknown-linux-gnu.replace]
  "org_old::dep" = { path = "./dep-new" }

  
[target.aarch64-unknown-linux-gnu.replace]
  "org_old::dep" = { path = "./dep-new" }

[target.x86_64-w64-mingw32.replace]
  "org_old::dep" = { path = "./dep-new" }

[target.x86_64-apple-darwin.replace]
  "org_old::dep" = { path = "./dep-new" }

[target.aarch64-apple-darwin.replace]
  "org_old::dep" = { path = "./dep-new" }

[package]
  cjc-version = "1.0.0"
  name = "demo"
  output-type = "executable"
  version = "1.0.0"
