[default]
APIStrategy = "Full"
GenericTypeStrategy = "None"

[[package]]
name = "cjworld"
APIStrategy = "Full"
GenericTypeStrategy = "Partial"
excluded_apis = [
]
tuple_configuration = [
    "(Int8, Int16, Int32, Int64, UInt16, Float32, Float64, Bool)",
    "(Int32, Int64)"
]
