# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "0.39.2"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "b"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}


[target.x86_64-unknown-linux-gnu]
  compile-option = "-O1"
 
[target.x86_64-unknown-linux-gnu.bin-dependencies]
  package-option = { "dep.aoo" = "dep/target/release/dep/dep.aoo.cjo" }
  path-option = ["dep/target/release/dep"]

[target.aarch64-unknown-linux-gnu]
  compile-option = "-O1"

[target.aarch64-unknown-linux-gnu.bin-dependencies]
  package-option = { "dep.aoo" = "dep/target/release/dep/dep.aoo.cjo" }
  path-option = ["dep/target/release/dep"]

[target.cjvm]
  compile-option = "-O2"
  [target.cjvm.bin-dependencies]
  path-option = ["dep/target/release/dep"]
  [target.cjvm.bin-dependencies.package-option]
  "dep.aoo" = "dep/target/release/dep/dep.aoo.cjo"

[target.x86_64-w64-mingw32]
  compile-option = "-O1"
 
[target.x86_64-w64-mingw32.bin-dependencies]
  package-option = { "dep.aoo" = "dep/target/release/dep/dep.aoo.cjo" }
  path-option = ["dep/target/release/dep"]
 
[target.x86_64-apple-darwin]
  compile-option = "-O1"
 
[target.x86_64-apple-darwin.bin-dependencies]
  package-option = { "dep.aoo" = "dep/target/release/dep/dep.aoo.cjo" }
  path-option = ["dep/target/release/dep"]
 
[target.aarch64-apple-darwin]
  compile-option = "-O1"
 
[target.aarch64-apple-darwin.bin-dependencies]
  package-option = { "dep.aoo" = "dep/target/release/dep/dep.aoo.cjo" }
  path-option = ["dep/target/release/dep"]

[target.aarch64-linux-ohos]
  compile-option = "-O1"
 
[target.aarch64-linux-ohos.bin-dependencies]
  package-option = { "dep.aoo" = "dep/target/release/dep/dep.aoo.cjo" }
  path-option = ["dep/target/release/dep"]