# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "0.50.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "test"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[target.x86_64-w64-mingw32.release]
link-option="--strip-all"

[target.x86_64-w64-mingw32.release.dependencies]
pro1={path="./pro1"}

[target.x86_64-w64-mingw32.debug.dependencies]
pro1={path="./pro1"}

[target.x86_64-unknown-linux-gnu.debug.dependencies]
pro1={path="./pro1"}

[target.x86_64-apple-darwin.dependencies]
  pro1={path="./pro1"}


[target. aarch64-linux-ohos.dependencies]
  pro1={path="./pro1"}
