# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
  pro1 = { path = "./pro1", output-type = "dynamic"}

[package]
  cjc-version = "0.50.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "testcase"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
