# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
  "org_old::dep" = { path = "../dep-old" }

[package]
  cjc-version = "1.0.0"
  name = "pro1"
  organization = "org_old"
  output-type = "static"
  version = "1.0.0"
