# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.0.0"
  name = "cj_project"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  output-type = "executable"
  compile-option = ""
  #override-compile-option = "-V"
  link-option = ""
  package-configuration = {}

[profile]
 experimental = true
  [profile.build]
    lto ="full"
    incremental = true
    performance_analysis = false
    compile-pipeline-parallel = false
  [profile.customized-option]
    debug = "-g -Woff all"
    release = "--fast-math -O2 -s -Woff all"
  [profile.build.combined]
  #  cj_project = "dynamic"

[package.package-configuration."cj_project"]
#combine-all-deps = true
[package.package-configuration."cj_project.a"]
#  output-type = "dynamic"


[dependencies]
pro0 = { path = "pro0" }