# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "0.26.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "test"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[target]
  [target.x86_64-unknown-linux-gnu]
    [target.x86_64-unknown-linux-gnu.bin-dependencies]
      path-option = []
      package-option = {pro1 = "pp/pro1/pro1.cjo"}

  [target.aarch64-unknown-linux-gnu]
    [target.aarch64-unknown-linux-gnu.bin-dependencies]
      path-option = []
      package-option = {pro1 = "pp/pro1/pro1.cjo"}

  [target.cjvm]
    [target.cjvm.bin-dependencies]
      path-option = []
      package-option = {pro1 = "pp/pro1/pro1.cjo"}

  [target.x86_64-w64-mingw32]
    [target.x86_64-w64-mingw32.bin-dependencies]
      path-option = []
      package-option = {pro1 = "pp/pro1/pro1.cjo"}

  [target.x86_64-apple-darwin]
    [target.x86_64-apple-darwin.bin-dependencies]
      path-option = []
      package-option = {pro1 = "pp/pro1/pro1.cjo"}

  [target.aarch64-apple-darwin]
    [target.aarch64-apple-darwin.bin-dependencies]
      path-option = []
      package-option = {pro1 = "pp/pro1/pro1.cjo"}

  [target.aarch64-linux-ohos]
    [target.aarch64-linux-ohos.bin-dependencies]
      path-option = []
      package-option = {pro1 = "pp/pro1/pro1.cjo"}
